name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Inno Setup
      uses: vercel/setup-innosetup@v1
      with:
        version: '6.2.0'  # Specify the Inno Setup version

    - name: Build Installer
      run: |
        iscc inno.iss

    - name: Upload Installer
      uses: actions/upload-artifact@v3
      with:
        name: setup-installer
        path: install/ZeedCom.Desktop.Setup.exe

    - name: Create Release
      id: create-release
      uses: gh-action-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Setup to Release
      uses: gh-action-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: install/ZeedCom.Desktop.Setup.exe
        asset_name: ZeedCom.Desktop.Setup.exe
        asset_content_type: application/octet-stream
